main: com.paratopiamc.colorbundles.ColorBundles
name: ColorBundles
version: 1.4
author: SolarRabbit
api-version: 1.17

softdepend: [ItemsAdder]

permissions:
  colorbundles.craft:
    description: User able to craft color bundles.
    default: true
