main: com.solarrabbit.colorbundles.ColorBundles
name: ColorBundles
version: ${project.version}
author: SolarRabbit
api-version: 1.17

softdepend: [ItemsAdder]

permissions:
  colorbundles.craft:
    description: User able to craft color bundles.
    default: true
