############################################################
# +------------------------------------------------------+ #
# |                      Model Data                      | #
# +------------------------------------------------------+ #
#                                                          #
#   Deconflict your custom model data here. Make sure      #
#   that the data here correctly corresponds to the data   #
#   in the resource pack. Keep custom model data to no     #
#   than 6 digits. DO NOT change model data once players   #
#   start crafting dyed bundles!                           #
#                                                          #
############################################################

black: 1101
blue: 1102
brown: 1103
cyan: 1104
gray: 1105
green: 1106
light_blue: 1107
light_gray: 1108
lime: 1109
magenta: 1110
orange: 1111
pink: 1112
purple: 1113
red: 1114
white: 1115
yellow: 1116
